### PR TITLE
feat(r-date-input): create r-date-input component

### PR DESCRIPTION
**Pull request by ZengJunyong**
Create Date/DateTime input component

### Check lists

- [x] Readme file updated with actual description and example
- [ ] Added all ARIA attributes required for component
- [x] Added tests for both browser and SSR render and for all components properties
- [x] Added story with all knobs and actions

### CODE REVIEW

**Comment by followyouhome** [comment]
Please fix disabled state and other knobs in storybook

**Comment by ZengJunyong** [comment]
> In the storybook I've tried disabled mode and it looks not good for date picker.
 
This bug is from r-input, @cesarlevel imported an undefined var:
`--input-icon-right-padding`, actually it should be
`--input-has-icon-right-padding`, typo LOL

**Comment by followyouhome** [comment]
Seems to be fixed, we definitely need to use our own calendar implementation in future.

**Comment by followyouhome** [comment]
Looks good as first step, but needs to be updated in future (at least remove v-calendar)

**Pull request merged**
