### PR TITLE
fix(r-toast): avoid quotes in animation scss to avoid invalid syntax error in gener…

### PR DESCRIPTION
**Pull request by agualis**
What was a problem?
Defining the r-toast animation with quotes in the scss file was causing an invalid generated css that prevented the animation from working.

### CODE REVIEW

**Comment by agualis** [comment]
@edtoken @rensftw I updated the PR (branch name and commit name to follow conventions).

@followyouhome please check the release things

**Comment by rensftw** [comment]
The commit message should be in the form of:
`<type>[optional scope]: <description>`
for example: `fix(r-toast): avoid quotes in animation scss to avoid invalid syntax error in generated css`

**Comment by agualis** [comment]
> (Edit: Looks like the PR title would be a valid conventional commit also :D)

I guess that when we do the squash we can edit the commit message and it will work. Right?

**Comment by agualis** [comment]
> PR title can do the trick (tested couple of months ago), but I think we should try to follow convection in commits.

Of course, from now on, I'll follow the convention. Thanks!

**Pull request merged**
