### PR TITLE
fix(all): Add polyfills support for IE 11

### PR DESCRIPTION
**Pull request by ZengJunyong**
### What was a problem?

Recomponents can't work well on IE11 as some features are not supported

### How this PR fixes the problem?

Added 2 polyfills:

- intersection-observer, fixed the r-lazy on IE11
- css-vars-ponyfill, maked the IE11 support css vars

and 

- if on IE11
    load the polyfills
- else 
    don't load

### Check lists

- [ ] Readme file updated with actual description and example
- [ ] Added all ARIA attributes required for component
- [ ] Added tests for both browser and SSR render and for all components properties
- [ ] Added story with all knobs and actions

### CODE REVIEW

**Comment by ZengJunyong** [comment]
Fixed the SSR issue, Just an idea, how to get the error once I submit the code? like unit tests or e2e tests?

**Comment by followyouhome** [comment]
After migration to github actions this can be possible - right now in travis we already waiting too long, but with actions we can run everything in parallel.

**Comment by followyouhome** [comment]
Sweet, thanks a lot 👍

**Pull request merged**
