### PR TITLE
fix(r-icon): load sprite only once

### PR DESCRIPTION
**Pull request by ZengJunyong**
When using `v-icon`,  `SVG Sprite` should be inserted to DOM only once, not multiple.

### CODE REVIEW

**Comment by followyouhome** [comment]
does it work with ssr (nuxt) w/o errors?

**Comment by ZengJunyong** [comment]
> does it work with ssr (nuxt) w/o errors?

I'll test it in SSR later, this PR is for Recomponent for now.

**Comment by followyouhome** [comment]
Let's not merge PRs that will broke existing functionality:

nuxt

Currently nuxt application doesn't work at all

**Comment by ZengJunyong** [comment]
Finally solved this bug, arrived below goals:

1.  Only load the sprites once in the DOM
2. Just use the <r-icon/>, no need to import <v-icon-sprites/>, which is different from Recomm
3. No bug(the document is undefined) in Nuxt.js

Look the VUE Lifecycle Diagram: https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram, we can use the `document` object in `created` and `mounted`, but in Nuxt.js, I tested it and found `document` object ONLY can be used in `mounted`, that's it!

**Pull request merged**
