### PR TITLE
Fix directive registration

### PR DESCRIPTION
**Pull request by mathewsonke**
### What was a problem?

Some directives were being registered in their own files, some in `index.js`. 

### How this PR fixes the problem?

This PR moves all directive registering into `index.js`. It also adds a proper `kebabCase` helper for registering the correct directive name.

### CODE REVIEW

**Comment by andrey-rebilly** [comment]
It seems okay to me (even though I don't know why tests are failing (lint issue)).
I would even go a step further - to have a simple script that loops through `/directives` folder and auto register them, removing the need to explicitly define them in `directives` object 😄

**Comment by followyouhome** [comment]
We tried same previously with components - this won't work in case you need to do something like:
`import { RButton } from '@rebilly/recomponents`

https://github.com/babel/babel/issues/2314

**Comment by followyouhome** [comment]
Please fix directive tests to proceed

**Comment by ZengJunyong** [comment]
`yarn test`, a lot of warning:
 **[Vue warn]: Failed to resolve directive: fs-block**

**Pull request merged**
