### PR TITLE
docs: update readme files

### PR DESCRIPTION
**Pull request by ZengJunyong**
English is my second language, hope someone can help me to improve it.

### CODE REVIEW

**Comment by followyouhome** [comment]
Same here - I think it's enough to regenerate snapshot in test

**Comment by ZengJunyong** [comment]
All checks have passed, wait for somebody from Montreal to review this PR cause English is my second language...

**Comment by adamaltman** [comment]
I read through the English and made a minor adjustment suggestion.  The English was fine.

**Pull request merged**
