### PR TITLE
Fix Nuxt demo

### PR DESCRIPTION
**Pull request by followyouhome**
### What was a problem?

Nuxt demo project is broken

### How this PR fixes the problem?

Adds missed object from DOM to avoid error 

### Check lists

- [ ] Readme file updated with actual description and example
- [ ] Added all ARIA attributes required for component
- [ ] Added tests for both browser and SSR render and for all components properties
- [ ] Added story with all knobs and actions

### CODE REVIEW

**Comment by ZengJunyong** [comment]
I got **HTMLElement is not defined**
image

**Comment by followyouhome** [comment]
@ZengJunyong this is exactly error I'd like to fix, could you please build local recomponents and copy them to nuxt's node_modules and check again?

**Comment by ZengJunyong** [comment]
Oh sorry, I forgot that, my bad!

**Pull request merged**
