### PR TITLE
fix(tools): decrease yarn version

### PR DESCRIPTION
**Pull request by followyouhome**
### What was a problem?

Cannot pass Travis build in another application

### How this PR fixes the problem?

Change version of yarn is enough to fix that issue

### CODE REVIEW

**Comment by slavcodev** [comment]
frontend please review

**Comment by mclassic** [comment]
I'm curious to learn more about this. Why is Travis failing on more recent Yarn versions?

**Comment by adamaltman** [comment]
> Cannot pass Travis build in another application

If another application uses a lower yarn version, it couldn't use this project.

**Comment by followyouhome** [comment]
Yes, I think me can update version when issue with workspaces will be fixed (on yarn side), but right not it's not critical

**Comment by ZengJunyong** [comment]
I merge it as I'd like to test it

**Pull request merged**
